version: '3'
services:
    service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - "3000:3000"
        volumes:
          - ../images:/home/app/images
        image: retkipaikka-backend:1
        container_name: retkipaikka-backend
        environment:
           - NODE_ENV=${NODE_ENV}
           - DB_HOST=${DB_HOST}
           - DB_DATABASE=${DB_DATABASE}
           - DB_PASSWORD=${DB_PASSWORD}
           - DB_USER=${DB_USER}
           - DATABASE_URL=${DB_URL}
           - LB_EMAIL=${LB_EMAIL}
           - DB_POSTGRES_EMAIL=${DB_POSTGRES_EMAIL}
           - DB_POSTGRES_PW=${DB_POSTGRES_PW}
           - USE_DB=${USE_DB}
           - SSL=${SSL}
        restart: always
        command: sh -c 'nodemon -r dotenv/config --exitcrash --watch common/ --watch server/' 
    db:
        image: "postgres"
        container_name: "retkipaikka-postgres"
        environment:
          - POSTGRES_DB=${DB_DATABASE}
          - POSTGRES_USER=${DB_USER}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
          - "54320:5432"
        volumes:
          - ../postgres-data:/var/lib/postgresql/data
    



