version: '3'
services:
    service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - "3000:3000"
        volumes:
          - ../images:/home/app/images
        image: retkipaikka-backend:1
        container_name: retkipaikka-backend
        restart: always
        command: sh -c 'nodemon --exitcrash --watch common/ --watch server/' 
    db:
        image: "postgres"
        container_name: "retkipaikka-postgres"
        environment:
          - POSTGRES_DB=${DB_DATABASE}
          - POSTGRES_USER=${DB_USER}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
          - "54320:5432"
        volumes:
          - ../postgres-data:/var/lib/postgresql/data



